### ISSUE TITLE
Add Recorder support

### ISSUE THREAD

**Issue by marshallpierce** [HdrHistogram/HdrHistogram_rust#51]
[Recorder](https://hdrhistogram.github.io/HdrHistogram/JavaDoc/org/HdrHistogram/Recorder.html) is really useful in real-world situations: one (or more) threads recording, with another thread occasionally inspecting the resulting histograms.

[synchronoise](https://github.com/QuietMisdreavus/synchronoise) has an implementation of [WriterReaderPhaser](https://stuff-gil-says.blogspot.com/2014/11/writerreaderphaser-story-about-new.html) that may prove useful.

**Comment by soro** [comment]
I'm currently working on this. It requires at least one implementation of a concurrent histogram and implementing one without a lot of duplication requires a decent amount of refactoring to extract the methods that compute new settings for the histogram.
I've implemented a WriterReaderPhaser and started the refactoring process.
Is anyone else working on this? I'm not going to get too much time to contribute for a couple more weeks, probably until roughly the end of the month, so if anyone else wants to start this in the meantime, I'll just make available what I have and hand it over.

**Comment by marshallpierce** [comment]
Nobody's actively working on this to my knowledge, but I'm glad you're making some headway on it. Recorders are very useful!

**Comment by soro** [comment]
So because I wanted to do quite a few things differently and experiment a bit, I basically wrote my own version from scratch, which you can find at https://github.com/soro/rusty-hdrhistogram. It's not fully feature complete yet, but a recorder is implemented. I haven't really had much time to work on this in the last few months and development has basically stalled since mid December, but I plan to get back to it soon and finish the rest.
Feel free to provide feedback or grab parts of it.

**Comment by jonhoo** [comment]
Out of curiosity, why did you decide to roll your own rather than change `HdrHistogram_rust`?

**Comment by soro** [comment]
I basically wrote quite different versions of large parts of the code base and there wasn't always a particularly good reason to replace what was there or it would have changed the interface somewhat. I also wanted to stick to names that were closer to the Java version etc.

**Comment by jonhoo** [comment]
I guess I'm asking why you had to write very different versions of large parts of the code? Unless I'm mistaken, adding both concurrency and recorder support should only require fairly minor changes? Having Java-compatible names could be achieved with a thin wrapper struct that just forwards methods with different names.

I'm trying to get a sense for whether there was something fundamental that made you feel as though *had* to make large changes, or whether you just wanted to :)

**Comment by jonhoo** [comment]
@marshallpierce I think it'd be really cool to use HdrHistogram as a metrics recording backend for [`metrics-rs`](https://github.com/metrics-rs/metrics), though that will definitely need support for this. I don't know how your spare time reserves are these days, but are you still interested in digging into this?

**Comment by marshallpierce** [comment]
Super interested, but super overstretched already. :cry:

**Comment by jonhoo** [comment]
I'll see if I can somehow dig up some time to do it. Or maybe I can try to convince one of the metrics-rs people to do it :eyes: Oooh, or maybe this would be a good live-stream topic..

**Comment by marshallpierce** [comment]
also note that https://docs.rs/synchronoise/1.0.0/synchronoise/ already has WriterReaderPhaser

**Comment by jonhoo** [comment]
@marshallpierce I think that's only one piece of the solution though, as we still need to support concurrently updating the histogram if I understand correctly.

Another design would be one in which each thread records to a thread-local histogram, and when a reader signals that it wants to read, it locks them all, merges the histograms, and then continues.

**Comment by marshallpierce** [comment]
If we lock, that would mean measurements themselves (i.e. storing to a histogram, or in this case a recorder) could be a significant source of pause times. See http://stuff-gil-says.blogspot.com/2014/11/writerreaderphaser-story-about-new.html for more on the phaser design. It's definitely not the whole answer but I think a locking-based approach and the corresponding timing unpredictability would make people sad, given that if they want to carefully measure times they probably also care about measurements being fast. :)

**Comment by jonhoo** [comment]
Ah, no, I'm not proposing that the readers take locks. Instead, they would get notified when the exclusive reader (which _would_ need a lock) wants to get an up-to-date histogram. At that point, they would collectively merge their histograms on their next write. You're right that that would still result in occasional pauses for the readers, but I think that's the case for the WriterReaderPhaser though --- occasionally the readers have to phase shift, which requires them doing more work.

**Comment by marshallpierce** [comment]
Hmm... I'm not following. How would the reader get a consistent snapshot of the histogram if the writer thread was either writing somewhere else (ala phaser) or locked?

**Comment by jonhoo** [comment]
I haven't thought this through completely, but my thinking would be that there is one local histogram per thread, and one global one. When the reader wants to read, it sets some shared variable to 1. When a writer sees that value as 1 on a write, it adds its local histogram to the global one (by locking it), clears its local one, and then notifies the reader that it has done so. When the reader gets that notification from all writers, it locks and reads from the global histogram. This way, writers generally only write to a local histogram, and only when the reader requires an up-to-date histogram do they synchronize. You could further optimize this at increased memory cost by having one global for each local, and require the reader to combine them all when reading. That way the writers would not even contend on the global lock.

**Comment by marshallpierce** [comment]
The latter is sort of what the Java Recorder impl does, I believe.

**Comment by jonhoo** [comment]
So, I _think_ this is a little different, as the recorders do not need to perform atomic operations on the histogram. They only perform local, non-atomic operations, and then occasionally "merge" their accumulated results into the global histogram. It does mean that they occasionally block (to merge), but it also means that the common-case of recording is faster. It _also_ means that we don't need to add a `ConcurrentHistogram` type!

**Comment by marshallpierce** [comment]
I'd love to get to a point where writers never block at all, but maybe that'll have to wait. What if we offload the "merging" to the readers?

**Comment by jonhoo** [comment]
Here's what I was thinking implemented: https://github.com/HdrHistogram/HdrHistogram_rust/blob/recorder/src/sync/mod.rs

I think truly wait-free recording is only available either with a concurrent histogram (i.e., atomic ops on counters), which would carry a much higher cost in general, or by keeping two histograms for every `Recorder` (and a phase shift swaps between them). The former _seems_ more expensive in the common case than the proposed approach, and the latter comes at twice the memory overhead. The solution above comes at no synchronization cost _at all_ during regular operation; it's only during phase shifts that it blocks.

One way that this _could_ be improved is to avoid the "all `Recorder`s have to merged into a single histogram on phase shift", and instead keep something like `log(n)` histograms and pick randomly among them to merge into, and then the reader does the final merge, but the speedup should only be noticeable for very large numbers of `Recorder`s.

One big issue with the current scheme, and I'd be curious to hear your thoughts on this, is that a phase shift _requires_ every `Recorder` to perform at least one `record` (or have called `Recorder::idle`). How onerous do you think that requirement is?

**Comment by marshallpierce** [comment]
Probably pretty onerous -- that means consumers would have to have some sort of idle timer, with all the associated plumbing, etc.

However, we could just have many flavors of Recorders named accordingly, and see what works in practice... we don't have to get it right the first time necessarily.

**Comment by jonhoo** [comment]
Another alternative would be to provide a timeout argument to `SyncHistogram::phase`, so that the reader doesn't have to block indefinitely.

**Comment by jonhoo** [comment]
Sadly I think it would be quite expensive to allow the reader to forcibly merge a `Recorder`'s state, even if the reader could somehow detect that a given `Recorder` is idle. It basically requires either double-buffering or concurrent counter values, neither of which are great. It might be that you can get to a good place by having each `Recorder` keep a `ConcurrentHistogram` (i.e., one that uses atomics for every counter), but that is also _significantly_ more work.

I'm inclined to land this first iteration in the first instance. The API seems reasonable, and we could always improve the implementation later. The `Recorder::synchronize`, `Recorder::idle`, and `SyncHistogram::phase_timeout` should also allow users to not have to worry too much about blocking issues. It basically gives bounded staleness, and lets the user control the bounds.

Thoughts?

**Comment by marshallpierce** [comment]
I'm happy with starting simple and iterating. Might want to name things (or possibly generify, if the impl shakes out that way) in such a way that we have room to change things in the future.

**Comment by jonhoo** [comment]
@marshallpierce I filed https://github.com/HdrHistogram/HdrHistogram_rust/pull/82; let's continue discussion there.
