### ISSUE TITLE
No way to append to an interval log? 

### ISSUE THREAD

**Issue by jonathanstrong** [HdrHistogram/HdrHistogram_rust#77]
Hey, great work on this library - enjoying working in it. I was wondering, was it intentional to design the api such that you can't append to interval logs? I had assumed that's what I'd be doing but realized eventually that would not work. Even if there was a stand-alone function or impl to serialize one `Histogram` into a Writer in the interval format, I think that would allow a lot of flexibility. Thanks!

**Comment by marshallpierce** [comment]
Glad you're enjoying it. :)

It's not something I specifically wanted to exclude, but usually interval logs are meant to record one particular run. Can you provide some more detail on what you're trying to do? Maybe there's a clever way to do it with the existing API, or maybe we need to rethink it. Are you opening and closing the file each time you write a histogram inside one long-running process?

**Comment by marshallpierce** [comment]
BTW, it looks like if you simply don't configure any of the extra goodies in `IntervalLogWriterBuilder`, it won't write any header data, so that should do what you want. Prepare an `io::Write` that's already been seeked to the end of the existing file, and append away.

**Comment by jonathanstrong** [comment]
My original plan was to keep one log file per day, but now I'm going to do one per run. I would have been opening and closing each time, partly because I'd like to read from the file while it's still being written to. I don't know if that will work or not if it's continually "open" inside the writer.

**Comment by jonathanstrong** [comment]
Oh, interesting. Do I need to insert a blank line in between the last previous record and the first new one?

**Comment by marshallpierce** [comment]
It shouldn't need a blank line, and each line should already have its trailing `\n`. Try running the result through the parser to be sure whatever you end up with is parseable. :)

If you keep the `IntervalLogWriter` alive, the file will remain open. One conceivable change would be to add an `into_write()` or something like that which would consume `self` and give you back the `Write`. You could then `flush()` or whatever you like.

**Comment by jonathanstrong** [comment]
A kind of hackey solution would also be to use scopes. Create the writer at the start with the metadata I want, let that go out of scope. Flush the writer I had provided the `&mut` to. Then each write of a `Histogram`, create a new writer, let it fall out of scope, and flush again.

**Comment by marshallpierce** [comment]
I'm guessing this is working now; re-open if not.
