### ISSUE TITLE
`fmt::Display` trait for errors

### ISSUE THREAD

**Issue by mexus** [HdrHistogram/HdrHistogram_rust#81]
Hi and thanks for a great library!

As the topic states, could it be possible to implement `Display` or even `Error` trait(s) for the crate's error types? I believe it will improve user experience and generally make it easier to incorporate those errors into the end-user's error type system :)

Thanks!

**Comment by jonhoo** [comment]
Ah, yes, that seems like a great idea! /cc @marshallpierce

**Comment by marshallpierce** [comment]
Absolutely. It was an oversight to not do so originally.

**Comment by jonhoo** [comment]
@mexus I don't know about @marshallpierce, but I'm currently pretty deep in work due to an upcoming paper deadline, but I'd be happy to take a look at a PR if you have the time to write something up :)

**Comment by marshallpierce** [comment]
I foolishly decided to start teaching at the local university on top of a full time job, so I have negative free time until the end of the semester, so if you want it done before May at the earliest, submitting a PR would be a help. :)

**Comment by mexus** [comment]
Okay I've got the point, will send a PR within a couple of days :)

Good luck with your quests, guys! Seems like you're having a lot of fun ;)

**Comment by mexus** [comment]
OMG I totally forgot about this issue, shame on me! :cry:  And thanks @AnderEnder for doing what I've promised to do half-a-year ago
