### ISSUE TITLE
Publish 7.0.0 to crates.io

### ISSUE THREAD

**Issue by svend** [HdrHistogram/HdrHistogram_rust#87]
Could you publish version 7.0.0 to crates.io? (I'm using the new Error types in 7.0.0.) Thanks for your work on this library!

**Comment by marshallpierce** [comment]
I haven't had time to do much with this project in a while but I can carve out the time to push a release at least. :) @jonhoo anything we should wait for before 7?

**Comment by jonhoo** [comment]
Oh, oops, I guess I forgot `cargo publish` :sweat_smile: Published!
